from words import Connector, Word, complex_word_builder, concept_builder

poki = Word(sound="poki", drawing="arc de cercle, ouvert, branches en haut")
anpa = Word(sound="anpa", drawing="barre horizontale, en bas")
na = Word(sound="na", drawing="lever de soleil")
telo = Word(sound="telo", drawing="gouttes", translation="eau")
kasi = Word(sound="kasi", drawing="arbre", translation="végétation")
suno = Word(sound="suno", drawing="trois rayons en haut")
waso = Word(sound="waso", drawing="dragon", translation="dragon")
kiwen = Word(sound="kiwen", drawing="triangle, pointe en bas", translation="montagne")
barre_horizontale_milieu = Word(drawing="barre -", translation="terre/sol")
barre_verticale = Word(drawing="barre '|'")
sina = Word(sound="sina", drawing="petite barre horizontale")
jan = Word(sound="jan", drawing="bonhomme sans bras debout", translation="humain")
jan_couche = Word(drawing="bonhomme -o", translation="mort/sommeil")
akesi = Word(sound="akesi", drawing="bonhomme sans bras couché en serpentin", translation="serpent")
noka = Word(sound="noka", drawing="pied", translation="pied")
taso = Word(
    sound="taso",
    drawing="barre verticale avec deux barres obliques en haut et au milieu, terminées par des petites barres horizontales",
)
nasi = Word(sound="nasi", drawing="is, avec une barre oblique en haut et un serpentin en bas")
ona = Word(sound="ona", drawing="barre oblique bas-gauche vers haut-droite")
ona_oppose = Word(drawing="barre /")
tawa = Word(sound="tawa", drawing="drapeau couché à gauche")
kama = Word(sound="kama", drawing="drapeau couché à droite")
nasin = Word(sound="nasin", drawing="ona, en serpentin")
toki = Word(sound="toki", drawing="E couché")
utala = Word(sound="utala", drawing="3 et 3 en miroir")
lili = Word(sound="lili", drawing="point", translation="petit")
pakala = Word(sound="pakala", drawing="éclair encadré dans un rectangle")
tomo = Word(sound="tomo", drawing="demi cercle fermé en bas")
seli = Word(sound="seli", drawing="point avec trois rayons vers le haut", translation="feu")
cercle = Word(drawing="cercle")
kulopo = Word(sound="kulopo", drawing="trois barres terminées par des cercles")
sinpin = Word(sound="sinpin", drawing="barre verticale avec un petit demi cercle au centre")
neka = Word(sound="neka", drawing="grande diagonale bas-gauche vers haut-droite en points")
pona = Word(sound="pona", drawing="barre horizontale avec petite barre verticale collée au milieu")
lukin = Word(sound="lukin", drawing="ovale en haut avec un point au centre")
sona = Word(sound="sona", drawing="cercle avec un point au centre")
kon = Word(sound="kon", drawing="deux petits s", translation="vent")
mute = Word(sound="mute", drawing="4 points en quinconce")
o = Word(sound="o", drawing="L", translation="à")
pana = Word(sound="pana", drawing="drapeau carré couché à droite")
mi = Word(sound="mi", drawing="petite barre verticale", translation="moi")
mani = Word(sound="mani", drawing="note de musique avec des crans", translation="dette")
tan = Word(sound="tan", drawing="petit angle en bas à gauche", translation="venant de")
kalama = Word(
    sound="kalama", drawing="diagonale bas-gauche vers haut-droite avec une boucle au centre", translation="cri"
)
palisa = Word(sound="palisa", drawing="rectangle vertical avec une barre horizontale au centre", translation="bâton")
lawa = Word(sound="lawa", drawing="mini barre verticale avec un gros garré au bout", translation="tête")
soweli = Word(sound="soweli", drawing="mounton", translation="animal")
en = Word(sound="en", drawing="eclair couché en deux parties", translation="avec/et")
pipi = Word(sound="pipi", drawing="bonhomme avec des jambes à la place de la tête")
kala = Word(sound="kala", drawing="poisson", translation="poisson")
kepeken = Word(sound="kepeken", drawing="barre horizontale avec un demi carré posé dessus")
mun = Word(sound="mun", drawing="trois points en haut")
pilin = Word(sound="pilin", drawing="bonhomme patate avec une vaguelette sur le coeur")
ilo = Word(sound="alo", drawing="T")
insu = Word(sound="insu", drawing="rond dans un carré")
nini = Word(sound="nini", drawing="cercle avec un trait bouclé vers le haut")
suli = Word(sound="suli", drawing="barres ||")


# Complex words
lape = complex_word_builder([barre_horizontale_milieu, sina], sound="lape")
noli = complex_word_builder([barre_horizontale_milieu, jan_couche], sound="noli")
Zehir = complex_word_builder([barre_horizontale_milieu, akesi], sound="zehir", translation="Zehir")
moku = complex_word_builder([barre_horizontale_milieu, toki], sound="moko")
laso = complex_word_builder([lukin, nasin, telo], sound="laso", translation="bleu")
jelo = complex_word_builder([lukin, nasin, suno], sound="jelo", translation="rouge")
ike = complex_word_builder([barre_horizontale_milieu, ona, ona_oppose], sound="ike")
wawa = complex_word_builder([ona_oppose, ona, ona, ona_oppose], sound="wawa")
tenpo = complex_word_builder([barre_horizontale_milieu, suno], sound="tenpo")
tu = complex_word_builder([barre_horizontale_milieu, suli], sound="tu")
wan = complex_word_builder([barre_horizontale_milieu, mi], sound="wan")
lon = complex_word_builder([barre_horizontale_milieu, mi], sound="lon")
awen = complex_word_builder([barre_verticale, mi], sound="awen")

# noms propres
narm = complex_word_builder([suno, waso, kiwen], sound="narm", translation="Narm")
python = complex_word_builder([suli, nasi, akesi], sound="python", translation="Python")
zadathar = complex_word_builder([waso, akesi, seli], sound="zadathar", translation="Zadathar")
loalas = complex_word_builder([tomo, kon], sound="loalas", translation="Loalas")
eberon = complex_word_builder([suno, soweli, na], sound="Eberon", translation="Eberon")  # pourquoi pas encadré ?
balthasar = complex_word_builder([kon, jan, utala], sound="Balthasar", translation="Balthasar")

# Connectors
li = Connector(sound="li", drawing="carré accroché à un angle")
pi = Connector(sound="li", drawing="aucun", translation="de", comment="annonce un encadrement de deux mots")
e = Connector(sound="e", drawing="petit cercle en bas")
la = Connector(sound="la", drawing="drapeau couché à gauche = tawa")
ni = Connector(sound="ni", drawing="<", translation=":")
e_ni = Connector(sound="e ni", drawing="e + ni")
point = Connector(drawing=".")
vide = Connector(drawing=" ")


# Concepts
Narm = concept_builder([narm], translation="Narm")
Python = concept_builder([python], translation="Python")
Zadathar = concept_builder([zadathar], translation="Zadathar")
Loalas = concept_builder([loalas], translation="Loalas")
Eberon = concept_builder([eberon], translation="Eberon")
Balthasar = concept_builder([balthasar], translation="Balthasar")

corne = concept_builder([palisa, lawa, soweli], translation="corne")
rugissement_corne_eberon = concept_builder([kalama, corne, eberon], translation="rugissement de la corne d'Eberon")
loalassien = concept_builder([jan, tan, loalas], translation="Loalassien")
moi_Zadathar = concept_builder([mi, zadathar, jelo], translation="moi, Zadathar le rouge")
